version: "3.9"

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - mongo
    env_file:
      - .env
  mongo:
    image: mongo
    ports:
      - "27017:27017"