version: "3"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        # For windows, volume only works if your files are under wsl
        volumes:
            - /app/node_modules
            - .:/app
