version: '3.3'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
  user-service:
    build:
      context: ./user-service
    ports:
      - '8000:8000'
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    env_file:
      - .env.local
  matching-service:
    build:
      context: ./matching-service
    ports:
      - '8001:8001'
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - user-service
      - matching-service
