version: "3.8"

services:
  nodeserver:
    build:
      context: .
    ports:
      - "8022:8022"
    env_file:
      - .env
    environment:
      ENV: production
      QUESTION_SERVICE_HOST: host.docker.internal
  peerjs-server:
    image: peerjs/peerjs-server
    ports:
      - "9000:9000"
