version: "3.3"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        links:
            - mongo
        env_file:
            - .env.testConfig
    mongo:
        image: mongo
        ports:
            - "27017:27017"
