version: "3.3"

services:
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        command:
            - "--logpath"
            - "/dev/null"
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
