apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: leetwithfriend-com-tls
spec:
  secretName: leetwithfriend-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: leetwithfriend.com
  dnsNames:
    - leetwithfriend.com
    - www.leetwithfriend.com
