apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching
  template:
    metadata:
      labels:
        app: matching
    spec:
      containers:
        - name: matching
          image: # TODO: push to docker hub
          ports:
            - name: http
              containerPort: 8001
          env:
            - name: PORT
              value: 80
            - name: URI_QUESTION_SERVICE
              value: http://question-cluster-ip-service:8500
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: cs3219
                  key: ACCESS_TOKEN_SECRET