apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question
  template:
    metadata:
      labels:
        app: question
    spec:
      containers:
        - name: question
          image: # TODO: push to docker hub
          ports:
            - name: http
              containerPort: 8000
