apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: b9jmthkk/user
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: DB_LOCAL_URI
              value: mongodb://mongo-cluster-ip-service:27017/peerprep
            - name: ENV
              value: production
            - name: PORT
              value: '80'
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: access-token-secret
                  key: ACCESS_TOKEN_SECRET
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: refresh-token-secret
                  key: REFRESH_TOKEN_SECRET
          resources:
            requests:
              cpu: 8m
              memory: 100Mi
