version: "3.8"
services:
    nodeserver:
        build:
            context: .
        ports:
            - "8001:8001"
        environment:
            ENV: production
            QUESTION_SERVICE_HOST: host.docker.internal