version: "3.8"

services:
  nodeserver:
    build:
      context: .
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      ENV: production
      HISTORY_SERVICE_HOST: host.docker.internal
      QUESTION_SERVICE_HOST: host.docker.internal
