version: '3.3'

services:
    postgres_db:
        image: postgres:latest
        restart: always
        ports:
            - '5432:5432'
        environment:
            ENV: production
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres_db
            POSTGRES_USER: postgres
            POSTGRES_HOST: host.docker.internal
            POSTGRES_PORT: 5432
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8500:8500'
        depends_on:
            - 'postgres_db'
        env_file:
            - .env.prod
        links:
            - postgres_db

