version: '3.3'

services:
    postgres_db:
        image: postgres:latest
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres_db
            POSTGRES_USER: postgres
            POSTGRES_HOST: postgres_db
            POSTGRES_PORT: 5432
        healthcheck:
            test:
                [
                    'CMD',
                    'pg_isready',
                    '-q',
                    '-d',
                    'postgres_db',
                    '-U',
                    'postgres',
                ]
            interval: 5s
            timeout: 5s
            retries: 5
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8500:8500'
        depends_on:
            postgres_db:
                condition: service_healthy
        environment:
            ENV: test
        env_file:
            - .env.prod
        links:
            - postgres_db
        restart: on-failure
        command: npm run test:ci
