name: Deploy RepoSense report

on:
  # For active deployment on push to main branch
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: tlylt/reposense-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Required
          cliArgs: '--since d1'
