name: History Service Test
on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: history-service
    steps:
      - uses: actions/checkout@v2
      - name: Test via docker-compose
        run: docker-compose -f docker-compose.test.yml up --exit-code-from web --build; docker rm $(docker ps -a --filter name=history-test -q)