name: Lint
on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  user-service-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: user-service
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - run: npm run lint:check
